[RevPi-2607] Made symlinks to copied files
RevolutionPi/revpi-eol-provisioner pull request #11
Opened 2022-12-22 11:11 UTC by hjokunbus

Device yaml files have to be handled in MS Windows environment. The Windows NTFS filesystem doesn't understand symbolic links, which leads to broken files on the target afterwards.

2022-12-22 11:14 UTC, nbuchwitz submitted a review, later dismissed

2022-12-22 11:26 UTC, naruxde requested changes
Some files must contain the data of _core-2022.yaml, at the moment all contains _core.yaml

<img width="251" alt="Bildschirm­foto 2022-12-22 um 12 26 06" src="https://user-images.githubusercontent.com/5154715/209124444-9b6c7d1f-51cd-4a8b-8943-a656d1f3ee6d.png">

2022-12-22 12:48 UTC, naruxde approved these changes

2022-12-22 13:00 UTC, nbuchwitz approved these changes

2022-12-23 05:40 UTC, RamiGspo approved these changes

2023-01-09 07:51 UTC, merged